// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in street/ent/runtime.go

const (
	Version = "v0.10.2-0.20220314134713-41db628df3cf"           // Version of ent codegen.
	Sum     = "h1:FhI9sridcJTArkg2CNnclYWSfMxY8diCQ6gBbXssD0U=" // Sum of ent codegen.
)
