CREATE TABLE "accounts" ("id" uuid NOT NULL, "sid" bigint NOT NULL, "create_time" timestamp(0)with time zone NOT NULL, "update_time" timestamp(0)with time zone NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "accounts_id_key" ON "accounts" ("id");
CREATE UNIQUE INDEX "accounts_sid_key" ON "accounts" ("sid");
CREATE UNIQUE INDEX "accounts_email_key" ON "accounts" ("email");
CREATE UNIQUE INDEX "account_email" ON "accounts" ("email");
CREATE TABLE "profiles" ("id" uuid NOT NULL, "sid" bigint NOT NULL, "create_time" timestamp(0)with time zone NOT NULL, "update_time" timestamp(0)with time zone NOT NULL, "title" character varying NOT NULL, "call" character varying NOT NULL, "category" character varying NOT NULL, "avatar" character varying NULL, "account_profile" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "profiles_accounts_profile" FOREIGN KEY ("account_profile") REFERENCES "accounts" ("id") ON DELETE NO ACTION);
CREATE UNIQUE INDEX "profiles_id_key" ON "profiles" ("id");
CREATE UNIQUE INDEX "profiles_sid_key" ON "profiles" ("sid");
CREATE UNIQUE INDEX "profiles_call_key" ON "profiles" ("call");
CREATE UNIQUE INDEX "profile_call" ON "profiles" ("call");
CREATE INDEX "profile_category" ON "profiles" ("category");
CREATE TABLE "series" ("id" uuid NOT NULL, "sid" bigint NOT NULL, "create_time" timestamp(0)with time zone NOT NULL, "update_time" timestamp(0)with time zone NOT NULL, "title" character varying NOT NULL, "type" character varying NULL, "profile_series" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "series_profiles_series" FOREIGN KEY ("profile_series") REFERENCES "profiles" ("id") ON DELETE NO ACTION);
CREATE UNIQUE INDEX "series_id_key" ON "series" ("id");
CREATE UNIQUE INDEX "series_sid_key" ON "series" ("sid");
CREATE TABLE "tokens" ("id" uuid NOT NULL, "sid" bigint NOT NULL, "create_time" timestamp(0)with time zone NOT NULL, "update_time" timestamp(0)with time zone NOT NULL, "body" character varying NOT NULL, "type" character varying NOT NULL, "expire" timestamp(0)with time zone NOT NULL, "account_token" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tokens_accounts_token" FOREIGN KEY ("account_token") REFERENCES "accounts" ("id") ON DELETE NO ACTION);
CREATE UNIQUE INDEX "tokens_id_key" ON "tokens" ("id");
CREATE UNIQUE INDEX "tokens_sid_key" ON "tokens" ("sid");
CREATE UNIQUE INDEX "tokens_body_key" ON "tokens" ("body");
CREATE UNIQUE INDEX "token_body" ON "tokens" ("body");
CREATE TABLE "profile_joined_series" ("profile_id" uuid NOT NULL, "series_id" uuid NOT NULL, PRIMARY KEY ("profile_id", "series_id"), CONSTRAINT "profile_joined_series_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id") ON DELETE CASCADE, CONSTRAINT "profile_joined_series_series_id" FOREIGN KEY ("series_id") REFERENCES "series" ("id") ON DELETE CASCADE);
CREATE TABLE "episodes" ("id" uuid NOT NULL, "sid" bigint NOT NULL, "create_time" timestamp(0)with time zone NOT NULL, "update_time" timestamp(0)with time zone NOT NULL, "cover" character varying NULL, "title" character varying NULL, "content" text NOT NULL, "files" bytea NOT NULL, "profile_episode" uuid NOT NULL, "series_episodes" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "episodes_profiles_episode" FOREIGN KEY ("profile_episode") REFERENCES "profiles" ("id") ON DELETE NO ACTION, CONSTRAINT "episodes_series_episodes" FOREIGN KEY ("series_episodes") REFERENCES "series" ("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "episodes_id_key" ON "episodes" ("id");
CREATE UNIQUE INDEX "episodes_sid_key" ON "episodes" ("sid");
CREATE TABLE "comments" ("id" uuid NOT NULL, "sid" bigint NOT NULL, "create_time" timestamp(0)with time zone NOT NULL, "update_time" timestamp(0)with time zone NOT NULL, "content" text NOT NULL, "episode_comments" uuid NOT NULL, "profile_commenter" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "comments_episodes_comments" FOREIGN KEY ("episode_comments") REFERENCES "episodes" ("id") ON DELETE NO ACTION, CONSTRAINT "comments_profiles_commenter" FOREIGN KEY ("profile_commenter") REFERENCES "profiles" ("id") ON DELETE NO ACTION);
CREATE UNIQUE INDEX "comments_id_key" ON "comments" ("id");
CREATE UNIQUE INDEX "comments_sid_key" ON "comments" ("sid");
CREATE TABLE "files" ("id" uuid NOT NULL, "sid" bigint NOT NULL, "create_time" timestamp(0)with time zone NOT NULL, "update_time" timestamp(0)with time zone NOT NULL, "filename" character varying NOT NULL DEFAULT 'file', "path" character varying NOT NULL DEFAULT 'media', "mime" character varying NOT NULL DEFAULT 'application/octet-stream', "size" bigint NOT NULL, "status" character varying NOT NULL DEFAULT 'created', "note" character varying NULL, "account_file" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "files_accounts_file" FOREIGN KEY ("account_file") REFERENCES "accounts" ("id") ON DELETE NO ACTION);
CREATE UNIQUE INDEX "files_id_key" ON "files" ("id");
CREATE UNIQUE INDEX "files_sid_key" ON "files" ("sid");
