version: "3.9"
services:
  database:
    image: "postgres:13-alpine3.15"
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ../.env
    volumes:
      - .develop/db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:23456:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]

  storage:
    image: "minio/minio"
    volumes:
      - ../.develop/files:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --address 0.0.0.0:9000 --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: "redis:6.2.6-alpine3.15"
    volumes:
      - ../.develop/redis:/data
    ports:
      - "6379:6379"

  asynqmon:
    image: "hibiken/asynqmon"
    ports:
      - "8889:8080"
    command: --redis-addr=redis:6379 --redis-db=1