// Code generated by entc, DO NOT EDIT.

package comment

import (
	"street/ent/schema"
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the comment type in the database.
	Label = "comment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSid holds the string denoting the sid field in the database.
	FieldSid = "sid"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// EdgeEpisode holds the string denoting the episode edge name in mutations.
	EdgeEpisode = "episode"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// EdgeReplyTo holds the string denoting the replyto edge name in mutations.
	EdgeReplyTo = "replyTo"
	// EdgeReplied holds the string denoting the replied edge name in mutations.
	EdgeReplied = "replied"
	// Table holds the table name of the comment in the database.
	Table = "comments"
	// EpisodeTable is the table that holds the episode relation/edge.
	EpisodeTable = "comments"
	// EpisodeInverseTable is the table name for the Episode entity.
	// It exists in this package in order to avoid circular dependency with the "episode" package.
	EpisodeInverseTable = "episodes"
	// EpisodeColumn is the table column denoting the episode relation/edge.
	EpisodeColumn = "episode_comments"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "comments"
	// AuthorInverseTable is the table name for the Profile entity.
	// It exists in this package in order to avoid circular dependency with the "profile" package.
	AuthorInverseTable = "profiles"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "profile_commenter"
	// ReplyToTable is the table that holds the replyTo relation/edge.
	ReplyToTable = "comments"
	// ReplyToColumn is the table column denoting the replyTo relation/edge.
	ReplyToColumn = "comment_replied"
	// RepliedTable is the table that holds the replied relation/edge.
	RepliedTable = "comments"
	// RepliedColumn is the table column denoting the replied relation/edge.
	RepliedColumn = "comment_replied"
)

// Columns holds all SQL columns for comment fields.
var Columns = []string{
	FieldID,
	FieldSid,
	FieldCreateTime,
	FieldUpdateTime,
	FieldContent,
	FieldPath,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "comments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"comment_replied",
	"episode_comments",
	"profile_commenter",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSid holds the default value on creation for the "sid" field.
	DefaultSid func() schema.ID
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultPath holds the default value on creation for the "path" field.
	DefaultPath string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
